### ISSUE TITLE
Build errors on node v6.7.0

### ISSUE THREAD

**Issue by crismancich** [memetolsen/node-red-grovepi-nodes#3]
WIth node 6.1.10 and npm 3.10.8
npm install node-red-grovepi-nodes fails at

i2c.target.mk:88: recipe for target 'Release/obj.target/i2c/src/i2c.o' failed
make: **\* [Release/obj.target/i2c/src/i2c.o] Error 1
make: Leaving directory '/usr/lib/node_modules/node-red/node_modules/i2c-bus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-red/node_modules/i2c-bus
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-red@0.14.6 /usr/lib/node_modules/node-red
└── (empty)

npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-grovepi-nodes"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! i2c-bus@0.11.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the i2c-bus@0.11.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the i2c-bus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs i2c-bus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls i2c-bus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/node-red/npm-debug.log
npm ERR! code 1
pi@raspberrypi:/usr/lib/node_modules/node-red $ 

Is this a version incompatibility or did I miss something?

**Comment by itarozzi** [comment]
The  same here,  jessie on raspberry pi 3

**Comment by memetolsen** [comment]
@crismancich Could you try again? @itarozzi  had the same problem and appearently his issue is fixed with the latest update: https://github.com/memetolsen/node-red-grovepi-nodes/pull/4
